DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS paper;
DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS user(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  auth TINYINT NOT NULL,
  id_auth BIGINT UNSIGNED NOT NULL,
  name NVARCHAR(64) NOT NULL,
  icon_url NVARCHAR(512) NOT NULL,
  registered_at DATETIME NOT NULL,
  UNIQUE(auth, id_auth),
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS paper(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  repo TINYINT NOT NULL,
  id_repo BIGINT UNSIGNED NOT NULL,
  UNIQUE(repo, id_repo),
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS review(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  paper_id INT UNSIGNED NOT NULL,
  rate TINYINT,
  comment TEXT,
  reviewed_at DATETIME NOT NULL,
  UNIQUE(user_id, paper_id),
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (paper_id) REFERENCES paper(id)
);
